config/routes.rb
Rails.application.routes.draw do
  resources :brands, except: :show
  resources :locations, except: :show
  resources :materials, except: :show
  resources :studios, except: :show
  resources :jewelries, except: :show

  get "/", to: redirect("/jewelries", status: 302)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/jewelry.rb
class Jewelry < ApplicationRecord
  belongs_to :brand
  belongs_to :studio
  belongs_to :location
  belongs_to :material

  delegated_type :jewelry_attributes, types: %w[
      AttributesCaptiveBeadRing
      AttributesChain
      AttributesCircularBarbell
      AttributesCurvedBarbell
      AttributesLabretPost
      AttributesPlug
      AttributesThreadedEnd
      AttributesThreadlessEnd
    ], dependent: :destroy
  accepts_nested_attributes_for :jewelry_attributes
end

app/controllers/jewelries_controller.rb
class JewelriesController < ApplicationController
  before_action :set_jewelry, only: %i[ edit update destroy ]
  before_action :set_jewelry_attribute_types, only: %i[ index new edit ]

  # GET /jewelries or /jewelries.json
  def index
    @jewelries = Jewelry.preload(:brand, :location, :material, :studio).all
  end

  # GET /jewelries/new
  def new
    new_attributes_type_name = request.query_parameters[:attributes]
    if @jewelry_attribute_types.include? new_attributes_type_name
      @jewelry = Jewelry.new(jewelry_attributes: new_attributes_type_name.constantize.new)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /jewelries/1/edit
  def edit
  end

  # POST /jewelries
  def create
    # debugger
    @jewelry = Jewelry.new(jewelry_params)

    if @jewelry.save
      redirect_to edit_jewelry_path(@jewelry), notice: "Jewelry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /jewelries/1
  def update
    if @jewelry.update(jewelry_params)
      redirect_to edit_jewelry_path(@jewelry), notice: "Jewelry was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /jewelries/1
  def destroy
    @jewelry.destroy!

    redirect_to jewelries_path, status: :see_other, notice: "Jewelry was successfully destroyed."
  end

  def get_jewelry_type_name (jewelry)
    @jewelry_attribute_type_names[jewelry.jewelry_attributes_type]
  end
  helper_method :get_jewelry_type_name

  def full_jewelry_type_name
    if @jewelry
      "#{@jewelry_attribute_type_names[@jewelry.jewelry_attributes_type]} jewelry"
    end
  end
  helper_method :full_jewelry_type_name

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jewelry
      @jewelry = Jewelry.find(params.expect(:id))
    end

    def set_jewelry_attribute_types
      # ["AttributesCaptiveBeadRing", ...]
      @jewelry_attribute_types = Jewelry.jewelry_attributes_types
      # prettify class names e.g. AttributesCaptiveBeadRing => "Captive Bead Ring"
      @jewelry_attribute_type_names = @jewelry_attribute_types.to_h { |type| [ type, type[10, 100].split(/(?=[A-Z])/).join(" ") ] }
    end

    # Only allow a list of trusted parameters through.
    def jewelry_params
      jewelry_base_params.merge({
        jewelry_attributes_attributes: jewelry_attribute_params
      })
    end

    def jewelry_base_params
      params.expect(jewelry: [ :name, :brand_id, :studio_id, :location_id, :material_id, :jewelry_attributes_type, jewelry_attributes_attributes: {} ])
    end

    def jewelry_attribute_params
      case jewelry_base_params[:jewelry_attributes_type]
      when "AttributesCaptiveBeadRing"
        jewelry_base_params.expect(jewelry_attributes_attributes: [ :id, :gauge, :ring_diameter, :bead_diameter ])
      when "AttributesChain"
        jewelry_base_params.expect(jewelry_attributes_attributes: [ :id, :length ])
      when "AttributesCircularBarbell"
        jewelry_base_params.expect(jewelry_attributes_attributes: [ :id, :gauge, :diameter ])
      when "AttributesCurvedBarbell"
        jewelry_base_params.expect(jewelry_attributes_attributes: [ :id, :gauge, :length ])
      when "AttributesLabretPost"
        jewelry_base_params.expect(jewelry_attributes_attributes: [ :id, :gauge, :length ])
      when "AttributesPlug"
        jewelry_base_params.expect(jewelry_attributes_attributes: [ :id, :gauge, :length ])
      when "AttributesThreadedEnd"
        jewelry_base_params.expect(jewelry_attributes_attributes: [ :id, :gauge, :diameter ])
      when "AttributesThreadlessEnd"
        jewelry_base_params.expect(jewelry_attributes_attributes: [ :id, :gauge, :diameter ])
      end
    end
end

app/views/jewelries/_form.html.erb
<%= app_form_with(model: jewelry) do |f| %>
  <%= f.input :name %>

  <%= f.input :brand_id, collection: Brand.all, text_method: :name, value_method: :id %>
  <%= f.input :location_id, collection: Location.all, text_method: :name, value_method: :id %>
  <%= f.input :material_id, collection: Material.all, text_method: :name, value_method: :id %>
  <%= f.input :studio_id, collection: Studio.all, text_method: :name, value_method: :id %>

  <%= hidden_field(:jewelry, :jewelry_attributes_type) %>

  <%= f.fields_for :jewelry_attributes do |f| %>
    <%= render "#{@jewelry.jewelry_attributes_class.name.underscore.pluralize}/form", f: f %>
  <% end %>

  <%= render "partials/form_save_or_delete", record: jewelry, f: f %>
<% end %>

app/views/jewelries/edit.html.erb
<% content_for :title, "Editing #{full_jewelry_type_name}" %>

<%= render "form", jewelry: @jewelry %>

app/views/jewelries/index.html.erb
<% content_for :title, "Jewelry" %>
<% content_for :header_aside do %>
  <%= app_form_with(url: new_jewelry_path, method: "get") do |f| %>
    <%= f.input :attributes,
      collection: @jewelry_attribute_types,
      text_method: proc { |type| @jewelry_attribute_type_names[type] },
      prompt: "New Jewelry",
      label: false,
      input_html: {onchange: "if (this.value !== '') this.form.requestSubmit()"}
      %>
  <% end %>
<% end %>

<%= render "table/table",
  fields: [
    {field: "name", title: "Name"},
    {lambda: proc { |jewelry| get_jewelry_type_name jewelry }, title: "Type" },
    {lambda: proc { |jewelry| jewelry.brand.name }, title: "Brand" },
    {lambda: proc { |jewelry| jewelry.location.name }, title: "Location" },
    {lambda: proc { |jewelry| jewelry.material.name }, title: "Material" },
    {lambda: proc { |jewelry| jewelry.studio.name }, title: "Studio" },
    {lambda: proc { |jewelry| link_to "View", edit_jewelry_path(jewelry), class: "underline" }, title: ""}
  ], 
  models: @jewelries
%>

app/views/jewelries/new.html.erb
<% content_for :title, "New #{full_jewelry_type_name}" %>

<%= render "form", jewelry: @jewelry %>