config/routes.rb
Rails.application.routes.draw do
  resources :brands, except: :show
  resources :locations, except: :show
  resources :materials, except: :show
  resources :studios, except: :show
  resources :jewelries, except: :show

  get "/", to: redirect("/jewelries", status: 302)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :jewelry, dependent: :destroy

  # validations
  validates :name, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ edit update destroy ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to edit_brand_path(@brand), notice: "Brand was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /brands/1
  def update
    if @brand.update(brand_params)
      redirect_to edit_brand_path(@brand), notice: "Brand was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /brands/1
  def destroy
    @brand.destroy!

    redirect_to brands_path, status: :see_other, notice: "Brand was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.expect(brand: [ :name, :website_url ])
    end
end

app/views/brands/_form.html.erb
<%= app_form_with(model: brand) do |f| %>
  <%= f.input :name %>
  <%= f.input :website_url %>

  <%= render "partials/form_save_or_delete", record: brand, f: f %>
<% end %>

app/views/brands/edit.html.erb
<% content_for :title, "Editing brand" %>

<%= render "form", brand: @brand %>

app/views/brands/index.html.erb
<% content_for :title, "Brands" %>
<% content_for :header_aside do %>
  <%= link_to "New Brand", new_brand_path, class: "btn" %>
<% end %>

<%= render "table/table",
  fields: [
    {field: "name", title: "Name"},
    {field: "website_url", title: "URL"},
    {lambda: proc { |brand| link_to "View", edit_brand_path(brand), class: "underline" }, title: ""}
  ], 
  models: @brands
%>

app/views/brands/new.html.erb
<% content_for :title, "New brand" %>

<%= render "form", brand: @brand %>