config/routes.rb
Rails.application.routes.draw do
  resources :brands, except: :show
  resources :locations, except: :show
  resources :materials, except: :show
  resources :studios, except: :show
  resources :jewelries, except: :show

  get "/", to: redirect("/jewelries", status: 302)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :jewelry, dependent: :destroy

  # validations
  validates :name, presence: true
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: %i[ edit update destroy ]

  # GET /materials or /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  def create
    @material = Material.new(material_params)

    if @material.save
      redirect_to edit_material_path(@material), notice: "Material was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /materials/1
  def update
    if @material.update(material_params)
      redirect_to edit_material_path(@material), notice: "Material was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /materials/1
  def destroy
    @material.destroy!

    redirect_to materials_path, status: :see_other, notice: "Material was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def material_params
      params.expect(material: [ :name ])
    end
end

app/views/materials/_form.html.erb
<%= app_form_with(model: material) do |f| %>
  <%= f.input :name %>

  <%= render "partials/form_save_or_delete", record: material, f: f %>
<% end %>

app/views/materials/edit.html.erb
<% content_for :title, "Editing material" %>

<%= render "form", material: @material %>

app/views/materials/index.html.erb
<% content_for :title, "Materials" %>
<% content_for :header_aside do %>
  <%= link_to "New Material", new_material_path, class: "btn" %>
<% end %>

<%= render "table/table",
  fields: [
    {field: "name", title: "Name"},
    {lambda: proc { |material| link_to "View", edit_material_path(material), class: "underline" }, title: ""}
  ], 
  models: @materials
%>

app/views/materials/new.html.erb
<% content_for :title, "New material" %>

<%= render "form", material: @material %>