config/routes.rb
Rails.application.routes.draw do
  resources :brands, except: :show
  resources :locations, except: :show
  resources :materials, except: :show
  resources :studios, except: :show
  resources :jewelries, except: :show

  get "/", to: redirect("/jewelries", status: 302)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :jewelry, dependent: :destroy

  # validations
  validates :name, presence: true
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: %i[ edit update destroy ]

  # GET /studios or /studios.json
  def index
    @studios = Studio.all
  end

  # GET /studios/new
  def new
    @studio = Studio.new
  end

  # GET /studios/1/edit
  def edit
  end

  # POST /studios
  def create
    @studio = Studio.new(studio_params)

    if @studio.save
      redirect_to edit_studio_path(@studio), notice: "Studio was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /studios/1
  def update
    if @studio.update(studio_params)
      redirect_to edit_studio_path(@studio), notice: "Studio was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /studios/1
  def destroy
    @studio.destroy!

    redirect_to studios_path, status: :see_other, notice: "Studio was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studio
      @studio = Studio.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def studio_params
      params.expect(studio: [ :name, :address, :website_url, :phone ])
    end
end

app/views/studios/_form.html.erb
<%= app_form_with(model: studio) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :website_url %>
  <%= f.input :phone %>

  <%= render "partials/form_save_or_delete", record: studio, f: f %>
<% end %>

app/views/studios/edit.html.erb
<% content_for :title, "Editing studio" %>

<%= render "form", studio: @studio %>

app/views/studios/index.html.erb
<% content_for :title, "Studios" %>
<% content_for :header_aside do %>
  <%= link_to "New Studio", new_studio_path, class: "btn" %>
<% end %>

<%= render "table/table",
  fields: [
    {field: "name", title: "Name"},
    {field: "address", title: "Address"},
    {field: "website_url", title: "URL"},
    {field: "phone", title: "Phone"},
    {lambda: proc { |studio| link_to "View", edit_studio_path(studio), class: "underline" }, title: ""}
  ], 
  models: @studios
%>

app/views/studios/new.html.erb
<% content_for :title, "New studio" %>

<%= render "form", studio: @studio %>